inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: "double_quotes"

Style/Documentation:
  Enabled: false

# see https://github.com/rubocop/ruby-style-guide/issues/329
# I am team "if not" (when it makes sense)
Style/NegatedIf:
  Enabled: false
