version: '3'

services:
  web:
    build: .
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
      - "12345:12345"
    environment:
      DATABASE_URL: 'postgresql://postgres:dummy@db:5433'
      RUBY_DEBUG_PORT: 12345
      RUBY_DEBUG_HOST: 0.0.0.0
      RUBY_DEBUG_NO_RELINE: true
      APLYPRO_ESTABLISHMENTS_BOOTSTRAP_URL: "http://mock:3002/list-etabs"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'dummy'
      PGPORT: 5433
    ports:
      - "5433:5433"
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 1090
    volumes:
      - .local/keycloak/:/opt/keycloak/data/
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    ports:
      - "3001:1090"
  mock:
    environment:
      PORT: 3002
    build:
      context: './mock'
    volumes:
      - "./mock:/app"
    ports:
      - "3002:3002"
