name: ci

on: push

# FIXME: having to run each step with every single environment
# variable just doesn't scale. We could stamp them straight into the
# image but that defeats the whole point of environment variables,
# lest we can do it just in this file.
env:
  DATABASE_URL: postgres://postgres:dummy@localhost:5432/test
  APLYPRO_SYGNE_URL: http://sygne/v1
  APLYPRO_SYGNE_TOKEN_URL: http://sygne/token
  APLYPRO_SYGNE_SECRET: CI sygne secret
  APLYPRO_SYGNE_CLIENT_ID: CI sygne client id
  RAILS_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          tags: aplypro:latest
          outputs: type=docker,dest=/tmp/aplypro.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Cache image
        id: aplypro-docker
        uses: actions/cache@v3
        with:
          path: /tmp/aplypro.tar
          key: ${{ github.sha }}-aplypro
  lint:
    name: "Linting: Rubocop"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/aplypro.tar
          key: ${{ github.sha }}-aplypro
      - run: docker load --input /tmp/aplypro.tar
      - run: docker run --rm --entrypoint="" aplypro:latest bundle exec rubocop
  unit-tests:
    name: "Unit tests: RSpec"
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: dummy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/aplypro.tar
          key: ${{ github.sha }}-aplypro
      - run: docker load --input /tmp/aplypro.tar
      - run: |
          docker run \
            --network="host" \
            -e DATABASE_URL \
            -e APLYPRO_SYGNE_URL \
            -e APLYPRO_SYGNE_CLIENT_ID \
            -e APLYPRO_SYGNE_SECRET \
            -e APLYPRO_SYGNE_TOKEN_URL \
            -e RAILS_ENV \
            --rm aplypro bundle exec rspec
  integration-tests:
    name: "Integration tests: Cucumber"
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: dummy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/aplypro.tar
          key: ${{ github.sha }}-aplypro
      - run: docker load --input /tmp/aplypro.tar
      - run: |
          docker run \
            --network="host" \
            -e DATABASE_URL \
            -e APLYPRO_SYGNE_URL \
            -e APLYPRO_SYGNE_CLIENT_ID \
            -e APLYPRO_SYGNE_SECRET \
            -e APLYPRO_SYGNE_TOKEN_URL \
            -e RAILS_ENV \
            --rm aplypro bundle exec cucumber
